FROM python:3.10
RUN apt-get update && apt-get -y install cron vim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY crontab /etc/cron.d/crontab
COPY app.py /app/app.py

RUN chmod 0644 /etc/cron.d/crontab
RUN /usr/bin/crontab /etc/cron.d/crontab

# run crond as main process of container
CMD ["cron", "-f"]