version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    networks:
      - middleware_bd_network

networks:
  middleware_bd_network:
    external: true